"""Initial migration

Revision ID: 41d036e396de
Revises: 
Create Date: 2023-04-26 06:55:39.096863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d036e396de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
                    sa.Column('version_num', sa.VARCHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'version_num', name='alembic_version_pkc')
                    )
    # ### end Alembic commands ###
