"""Add primary_portfolio_id to User model

Revision ID: ed2785d1d715
Revises: 41d036e396de
Create Date: 2023-05-01 05:55:56.608140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2785d1d715'
down_revision = '41d036e396de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('alembic_version')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column(
        'is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column(
        'primary_portfolio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'portfolios', [
                          'primary_portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'primary_portfolio_id')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    # )
    # ### end Alembic commands ###
